app-id: com.qq.qqmusic
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
base: org.electronjs.Electron2.BaseApp
base-version: '24.08'
command: qqmusic

finish-args:
  - --share=ipc
  - --socket=wayland
  - --socket=fallback-x11
  - --socket=pulseaudio
  - --device=dri
  - --share=network
  - --talk-name=org.kde.StatusNotifierWatcher
  - --own-name=org.mpris.MediaPlayer2.chromium.*
  # required to fix cursor scaling on wayland
  - --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons

add-extensions:
  org.freedesktop.Platform.Electron:
    version: '24.08'
    directory: electron

cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc

modules:
  - name: qqmusic
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - mkdir -p ${FLATPAK_DEST}/qqmusic
      - mkdir -p ${FLATPAK_DEST}/electron
      - install -Dm644 app.asar -t ${FLATPAK_DEST}/qqmusic
      - install -Dm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo
      - install -Dm644 ${FLATPAK_ID}.desktop -t ${FLATPAK_DEST}/share/applications
      - install -Dm644 ${FLATPAK_ID}.png -t ${FLATPAK_DEST}/share/icons/hicolor/256x256/apps/
      - install -Dm755 qqmusic.sh ${FLATPAK_DEST}/bin/qqmusic
    sources:
      - type: file
        path: com.qq.qqmusic.metainfo.xml
      - type: file
        path: com.qq.qqmusic.desktop
      - type: file
        path: com.qq.qqmusic.png
      - type: file
        dest-filename: app.asar
        url: https://q.askk.cc/qqmusic_1.1.7-1.asar
        sha256: 08a67db579fd49b4f644573a8c17efde822419791e24c37d84aaf455b30843a0
      - type: script
        dest-filename: qqmusic.sh
        commands:
          - export TMPDIR=${XDG_RUNTIME_DIR}/app/${FLATPAK_ID}
          - WAYLAND_SOCKET=${WAYLAND_DISPLAY:-"wayland-0"}
          - |
            if [[ -e "${XDG_RUNTIME_DIR}/${WAYLAND_SOCKET}" || -e "${WAYLAND_DISPLAY}" ]]
            then
                FLAGS="--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime --wayland-text-input-version=3"
            fi
          - exec zypak-wrapper "/app/electron/electron" "/app/qqmusic/app.asar" $FLAGS "$@"
