# And now, WebkitGTK and its deps *specifically.*
# Big thanks to Telegram Desktop Webview's manifest maintainers for this.
# Because I took pretty much the whole stupid thing and refactored it into its
# own yml file. I then added many extra parts from all over the Flathub org.
# Anyone who needs to include webkitgtk, *please* feel free to use this.

name: webkit2gtk-4.0
buildsystem: cmake-ninja
config-opts:
  - -DCMAKE_BUILD_TYPE=RelWithDebInfo
  - -DPORT=GTK
  - -DUSE_GTK4=OFF
  - -DUSE_SOUP2=ON  # This makes it build webkit2gtk-4.0 instead of 4.1.
  - -DUSE_LIBSECRET=OFF
  - -DUSE_LIBBACKTRACE=OFF
  - -DENABLE_GAMEPAD=OFF
  - -DENABLE_INTROSPECTION=OFF
  - -DENABLE_SPELLCHECK=OFF
  - -DENABLE_DOCUMENTATION=OFF
  - -DENABLE_MINIBROWSER=OFF
  - -DENABLE_BUBBLEWRAP_SANDBOX=OFF  # Unused inside of flatpak
sources:
  - type: archive
    url: https://webkitgtk.org/releases/webkitgtk-2.44.2.tar.xz
    sha256: 523f42c8ff24832add17631f6eaafe8f9303afe316ef1a7e1844b952a7f7521b
    x-checker-data:
      type: html
      url: https://webkitgtk.org/releases/
      version-pattern: LATEST-STABLE-(\d[\.\d]+\d)
      url-template: https://webkitgtk.org/releases/webkitgtk-$version.tar.xz
  - type: shell
    commands:
      - sed -i 's@NAMES avif.h@NAMES avif/avif.h@' Source/cmake/FindAVIF.cmake
      - sed -i '/PATH_SUFFIXES avif/d' Source/cmake/FindAVIF.cmake
      - sed -i 's@${AVIF_INCLUDE_DIR}/avif.h@${AVIF_INCLUDE_DIR}/avif/avif.h@' Source/cmake/FindAVIF.cmake
modules:

  - shared-modules/libsoup/libsoup-2.4.json

  - name: unifdef
    no-autogen: true
    make-install-args:
      - prefix=${FLATPAK_DEST}
    sources:
      - type: archive
        url: https://dotat.at/prog/unifdef/unifdef-2.12.tar.xz
        sha256: 43ce0f02ecdcdc723b2475575563ddb192e988c886d368260bc0a63aee3ac400
        x-checker-data:
          type: anitya
          project-id: 5046
          url-template: https://dotat.at/prog/unifdef/unifdef-$version.tar.xz
    cleanup:
      - '*'
  - name: highway
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DBUILD_SHARED_LIBS=ON
      - -DBUILD_TESTING=OFF
      - -DHWY_ENABLE_CONTRIB=OFF
      - -DHWY_ENABLE_EXAMPLES=OFF
    sources:
      - type: archive
        url: https://github.com/google/highway/archive/1.2.0/highway-1.2.0.tar.gz
        sha256: 7e0be78b8318e8bdbf6fa545d2ecb4c90f947df03f7aadc42c1967f019e63343
        x-checker-data:
          type: json
          url: https://api.github.com/repos/google/highway/releases/latest
          tag-query: .tag_name
          timestamp-query: .published_at
          version-query: $tag
          url-query: '"https://github.com/google/highway/archive/\($tag)/highway-\($version).tar.gz"'
  - name: woff2
    buildsystem: cmake-ninja
    builddir: true
    sources:
      - type: archive
        url: https://github.com/google/woff2/archive/v1.0.2.tar.gz
        sha256: add272bb09e6384a4833ffca4896350fdb16e0ca22df68c0384773c67a175594
        x-checker-data:
          type: anitya
          project-id: 17587
          url-template: https://github.com/google/woff2/archive/v$version.tar.gz
  - name: libavif
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DAVIF_CODEC_DAV1D=ON
      - -DBUILD_SHARED_LIBS=ON
    sources:
      - type: archive
        url: https://github.com/AOMediaCodec/libavif/archive/v1.0.4/libavif-1.0.4.tar.gz
        sha256: dc56708c83a4b934a8af2b78f67f866ba2fb568605c7cf94312acf51ee57d146
        x-checker-data:
          type: json
          url: https://api.github.com/repos/AOMediaCodec/libavif/releases/latest
          tag-query: .tag_name
          timestamp-query: .published_at
          version-query: $tag | sub("^[vV]"; "")
          url-query: '"https://github.com/AOMediaCodec/libavif/archive/\($tag)/libavif-\($version).tar.gz"'
  - name: libjxl
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DBUILD_TESTING=OFF
      - -DJPEGXL_ENABLE_DEVTOOLS=OFF
      - -DJPEGXL_ENABLE_TOOLS=OFF
      - -DJPEGXL_ENABLE_DOXYGEN=OFF
      - -DJPEGXL_ENABLE_MANPAGES=OFF
      - -DJPEGXL_ENABLE_BENCHMARK=OFF
      - -DJPEGXL_ENABLE_EXAMPLES=OFF
      - -DJPEGXL_ENABLE_JNI=OFF
      - -DJPEGXL_ENABLE_SJPEG=OFF
      - -DJPEGXL_ENABLE_OPENEXR=OFF
      - -DJPEGXL_ENABLE_SKCMS=OFF
      - -DJPEGXL_FORCE_SYSTEM_BROTLI=ON
      - -DJPEGXL_FORCE_SYSTEM_LCMS2=ON
      - -DJPEGXL_FORCE_SYSTEM_HWY=ON
    sources:
      - type: archive
        url: https://github.com/libjxl/libjxl/archive/v0.10.2/libjxl-0.10.2.tar.gz
        sha256: 95e807f63143856dc4d161c071cca01115d2c6405b3d3209854ac6989dc6bb91
        x-checker-data:
          type: json
          url: https://api.github.com/repos/libjxl/libjxl/releases/latest
          tag-query: .tag_name
          timestamp-query: .published_at
          version-query: $tag | sub("^[vV]"; "")
          url-query: '"https://github.com/libjxl/libjxl/archive/\($tag)/libjxl-\($version).tar.gz"'
  - name: libwpe
    buildsystem: meson
    builddir: true
    config-opts:
      - --buildtype=plain
    sources:
      - type: archive
        url: https://github.com/WebPlatformForEmbedded/libwpe/releases/download/1.16.0/libwpe-1.16.0.tar.xz
        sha256: c7f3a3c6b3d006790d486dc7cceda2b6d2e329de07f33bc47dfc53f00f334b2a
        x-checker-data:
          type: json
          url: https://api.github.com/repos/WebPlatformForEmbedded/libwpe/releases/latest
          tag-query: .tag_name
          timestamp-query: .published_at
          version-query: $tag
          url-query: '"https://github.com/WebPlatformForEmbedded/libwpe/releases/download/\($tag)/libwpe-\($version).tar.xz"'
  - name: wpebackend-fdo
    buildsystem: meson
    builddir: true
    config-opts:
      - --buildtype=plain
    sources:
      - type: archive
        url: https://github.com/Igalia/WPEBackend-fdo/releases/download/1.14.2/wpebackend-fdo-1.14.2.tar.xz
        sha256: 93c9766ae9864eeaeaee2b0a74f22cbca08df42c1a1bdb55b086f2528e380d38
        x-checker-data:
          type: json
          url: https://api.github.com/repos/Igalia/WPEBackend-fdo/releases/latest
          tag-query: .tag_name
          timestamp-query: .published_at
          version-query: $tag
          url-query: '"https://github.com/Igalia/WPEBackend-fdo/releases/download/\($tag)/wpebackend-fdo-\($version).tar.xz"'
