app-id: io.github.slotsun.slive
runtime: org.freedesktop.Platform
runtime-version: '25.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.llvm21
command: Slive
rename-icon: logo
rename-desktop-file: io.github.SlotSun.dart_simple_live.desktop
rename-appdata-file: io.github.SlotSun.dart_simple_live.metainfo.xml
finish-args:
  - --socket=wayland
  - --socket=pulseaudio
  - --share=network
  - --device=dri
  - --talk-name=org.freedesktop.ScreenSaver
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-docmodules

modules:
  - name: slive
    buildsystem: simple
    build-options:
      build-args:
        - --share=network
      arch:
        x86_64:
          env:
            BUNDLE_PATH: simple_live_app/build/linux/x64/release/bundle
        aarch64:
          env:
            BUNDLE_PATH: simple_live_app/build/linux/arm64/release/bundle
      append-path: /usr/lib/sdk/llvm21/bin:/run/build/slive/flutter/bin
      prepend-ld-library-path: /usr/lib/sdk/llvm21/lib
      env:
        PUB_CACHE: /run/build/slive/.pub-cache
    build-commands:
      - cd simple_live_app && flutter build linux --release
      - install -dvm755 ${FLATPAK_DEST}/bin
      - cp -av ${BUNDLE_PATH}/* ${FLATPAK_DEST}/bin
      - install -Dvm644 simple_live_app/assets/io.github.SlotSun.dart_simple_live.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo
      - install -Dvm644 simple_live_app/assets/images/logo.png -t ${FLATPAK_DEST}/share/icons/hicolor/512x512/apps
      - install -Dvm644 simple_live_app/assets/io.github.SlotSun.dart_simple_live.desktop -t ${FLATPAK_DEST}/share/applications
    sources:
      - type: git
        url: https://github.com/SlotSun/dart_simple_live
        # tag: v1.7.18
        commit: 05c0dd83069e054a63f818f5b6117e832088349f
        # x-checker-data:
        #   type: git
        #   tag-pattern: ^v([\d.]+)$
        #   is-main-source: true
      - type: git
        url: https://github.com/flutter/flutter.git
        tag: 3.38.4
        commit: 66dd93f9a27ffe2a9bfc8297506ce066ff51265f
        dest: flutter
        x-checker-data:
          type: git
          tag-pattern: ^([\d.]+)$
