app-id: io.github.SlotSun.Slive
runtime: org.freedesktop.Platform
runtime-version: '25.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.llvm21
command: io.github.SlotSun.Slive
finish-args:
  - --socket=wayland
  - --socket=pulseaudio
  - --share=network
  - --device=dri
  - --talk-name=org.freedesktop.ScreenSaver
  # user settings synchronization feature requires this D-Bus
  - --system-talk-name=org.freedesktop.NetworkManager.IP4Config
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-docmodules

modules:
  - name: rustup
    buildsystem: simple
    build-options:
      build-args:
        - --share=network
      env:
        CARGO_HOME: /var/lib/rustup
        RUSTUP_HOME: /var/lib/rustup
    build-commands:
      - chmod -v +x rustup-init && ./rustup-init -y --profile minimal --no-modify-path
    sources:
      - type: file
        only-arches: [x86_64]
        url: https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
        sha256: 20a06e644b0d9bd2fbdbfd52d42540bdde820ea7df86e92e533c073da0cdd43c
      - type: file
        only-arches: [aarch64]
        url: https://static.rust-lang.org/rustup/dist/aarch64-unknown-linux-gnu/rustup-init
        sha256: e3853c5a252fca15252d07cb23a1bdd9377a8c6f3efa01531109281ae47f841c

  - name: Slive
    buildsystem: simple
    build-options:
      build-args:
        - --share=network
      arch:
        x86_64:
          env:
            BUNDLE_PATH: simple_live_app/build/linux/x64/release/bundle
        aarch64:
          env:
            BUNDLE_PATH: simple_live_app/build/linux/arm64/release/bundle
      append-path: /var/lib/rustup/bin:/usr/lib/sdk/llvm21/bin:/run/build/Slive/flutter/bin
      prepend-ld-library-path: /usr/lib/sdk/llvm21/lib
      env:
        RUSTUP_HOME: /var/lib/rustup
        CARGO_HOME: /var/lib/rustup
        PUB_CACHE: /run/build/Slive/.pub-cache
    build-commands:
      - cd simple_live_app && flutter build linux --release
      - install -dvm755 ${FLATPAK_DEST}/bin
      - cp -av ${BUNDLE_PATH}/* ${FLATPAK_DEST}/bin
      - install -Dvm644 simple_live_app/assets/${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo
      - install -Dvm644 simple_live_app/assets/images/logo.png ${FLATPAK_DEST}/share/icons/hicolor/512x512/apps/${FLATPAK_ID}.png
      - install -Dvm644 simple_live_app/assets/${FLATPAK_ID}.desktop -t ${FLATPAK_DEST}/share/applications
    sources:
      - type: git
        url: https://github.com/SlotSun/dart_simple_live
        tag: v1.8.7
        commit: 23a09a35b30e2180824ccd9038879868578fa8fa
        x-checker-data:
          type: git
          tag-pattern: ^v([\d.]+)$
          is-main-source: true
      - type: git
        url: https://github.com/flutter/flutter.git
        tag: 3.38.9
        commit: 67323de285b00232883f53b84095eb72be97d35c
        dest: flutter
        x-checker-data:
          type: git
          tag-pattern: ^([\d.]+)$
