app-id: app.reeden.reeden
runtime: org.freedesktop.Platform
runtime-version: '25.08'
sdk: org.freedesktop.Sdk
command: reeden

finish-args:
  - --share=network
  - --socket=wayland
  - --socket=pulseaudio
  - --device=dri
  - --own-name=app.reeden

cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc

modules:
  - name: curl
    buildsystem: autotools
    config-opts:
      - --with-openssl
      - --enable-versioned-symbols
    sources:
      - type: archive
        url: https://github.com/curl/curl/releases/download/curl-8_18_0/curl-8.18.0.tar.xz
        sha256: 40df79166e74aa20149365e11ee4c798a46ad57c34e4f68fd13100e2c9a91946
        x-checker-data:
          type: json
          url: https://api.github.com/repos/curl/curl/releases/latest
          version-query: .tag_name | sub("^curl-"; "") | gsub("_"; ".")
          url-query: .assets[] | select(.name=="curl-" + $version + ".tar.xz") | .browser_download_url

  - name: reeden
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - install -Dvm755 apply_extra.sh ${FLATPAK_DEST}/bin/apply_extra
      - install -Dvm755 reeden.sh ${FLATPAK_DEST}/bin/reeden
      - install -Dvm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo
      - install -Dvm644 ${FLATPAK_ID}.desktop -t ${FLATPAK_DEST}/share/applications
      - install -Dvm644 ${FLATPAK_ID}.png -t ${FLATPAK_DEST}/share/icons/hicolor/512x512/apps
    sources:
      - type: script
        commands:
          - exec "/app/extra/reeden/reeden" "$@"
        dest-filename: reeden.sh

      - type: script
        commands:
          - bsdtar --to-stdout -xvf reeden.deb data.* | bsdtar -xvf -
          - mv -v usr/share/reeden .
          - rm -rv reeden.deb usr
        dest-filename: apply_extra.sh

      - type: file
        path: app.reeden.reeden.metainfo.xml

      - type: file
        path: app.reeden.reeden.desktop

      - type: file
        path: app.reeden.reeden.png

      - type: extra-data
        filename: reeden.deb
        only-arches: [x86_64]
        url: https://github.com/reeden-org/reeden-app/releases/download/v1.25.2/Reeden-linux-x86_64.deb
        sha256: 6e3d8ad75256abf35999e75e1814210cae0e81ca16da52108379ecdf6a9ee1d2
        size: 34862588
        x-checker-data:
          type: json
          url: https://api.github.com/repos/reeden-org/reeden-app/releases/latest
          is-main-source: true
          version-query: .tag_name | sub("^v"; "")
          url-query: >-
            .assets[] | select(.name=="Reeden-linux-x86_64.deb") | .browser_download_url
